pve_pigeons_list = {
    1: [
        {"pigeon_type": 1, "luck": 20},
        {"pigeon_type": 1, "luck": 20},
        {"pigeon_type": 2, "luck": 20},
        {"pigeon_type": 2, "luck": 20},
        {"pigeon_type": 3, "luck": 20},
    ],
    2: [
        {"pigeon_type": 2, "luck": 20},
        {"pigeon_type": 2, "luck": 20},
        {"pigeon_type": 2, "luck": 40},
        {"pigeon_type": 2, "luck": 40},
        {"pigeon_type": 2, "luck": 40},
    ],
    3: [
        {"pigeon_type": 1, "luck": 20},
        {"pigeon_type": 1, "luck": 20},
        {"pigeon_type": 1, "luck": 40},
        {"pigeon_type": 1, "luck": 40},
        {"pigeon_type": 1, "luck": 40},
    ],
    4: [
        {"pigeon_type": 3, "luck": 20},
        {"pigeon_type": 3, "luck": 20},
        {"pigeon_type": 3, "luck": 40},
        {"pigeon_type": 3, "luck": 40},
        {"pigeon_type": 3, "luck": 40},
    ],
    5: [
        {"pigeon_type": 2, "luck": 40},
        {"pigeon_type": 2, "luck": 40},
        {"pigeon_type": 2, "luck": 60},
        {"pigeon_type": 2, "luck": 40},
        {"pigeon_type": 1, "luck": 60},
    ],
    6: [
        {"pigeon_type": 1, "luck": 60},
        {"pigeon_type": 1, "luck": 60},
        {"pigeon_type": 1, "luck": 60},
        {"pigeon_type": 1, "luck": 60},
        {"pigeon_type": 3, "luck": 40},
    ],
    7: [
        {"pigeon_type": 3, "luck": 60},
        {"pigeon_type": 3, "luck": 60},
        {"pigeon_type": 3, "luck": 60},
        {"pigeon_type": 3, "luck": 80},
        {"pigeon_type": 1, "luck": 80},
    ],
    8: [
        {"pigeon_type": 2, "luck": 80},
        {"pigeon_type": 2, "luck": 80},
        {"pigeon_type": 2, "luck": 80},
        {"pigeon_type": 2, "luck": 80},
        {"pigeon_type": 1, "luck": 80},
    ],
    9: [
        {"pigeon_type": 1, "luck": 80},
        {"pigeon_type": 1, "luck": 80},
        {"pigeon_type": 1, "luck": 80},
        {"pigeon_type": 3, "luck": 80},
        {"pigeon_type": 1, "luck": 90},
    ],
    10: [
        {"pigeon_type": 1, "luck": 80},
        {"pigeon_type": 3, "luck": 90},
        {"pigeon_type": 3, "luck": 90},
        {"pigeon_type": 3, "luck": 80},
        {"pigeon_type": 3, "luck": 90},
    ],
    11: [
        {"pigeon_type": 1, "luck": 90},
        {"pigeon_type": 2, "luck": 90},
        {"pigeon_type": 2, "luck": 95},
        {"pigeon_type": 2, "luck": 90},
        {"pigeon_type": 2, "luck": 90},
    ],
    12: [
        {"pigeon_type": 1, "luck": 95},
        {"pigeon_type": 1, "luck": 95},
        {"pigeon_type": 1, "luck": 95},
        {"pigeon_type": 1, "luck": 95},
        {"pigeon_type": 2, "luck": 95},
    ],
    13: [
        {"pigeon_type": 1, "luck": 95},
        {"pigeon_type": 1, "luck": 95},
        {"pigeon_type": 2, "luck": 95},
        {"pigeon_type": 2, "luck": 95},
        {"pigeon_type": 2, "luck": 95},
    ],
    14: [
        {"pigeon_type": 1, "luck": 95},
        {"pigeon_type": 1, "luck": 95},
        {"pigeon_type": 2, "luck": 95},
        {"pigeon_type": 2, "luck": 95},
        {"pigeon_type": 3, "luck": 95},
    ],
    15: [
        {"pigeon_type": 1, "luck": 95},
        {"pigeon_type": 2, "luck": 95},
        {"pigeon_type": 2, "luck": 95},
        {"pigeon_type": 3, "luck": 95},
        {"pigeon_type": 3, "luck": 95},
    ],
    16: [
        {"pigeon_type": 2, "luck": 100},
        {"pigeon_type": 2, "luck": 100},
        {"pigeon_type": 2, "luck": 100},
        {"pigeon_type": 2, "luck": 100},
        {"pigeon_type": 2, "luck": 100},
    ],
    17: [
        {"pigeon_type": 1, "luck": 100},
        {"pigeon_type": 1, "luck": 100},
        {"pigeon_type": 1, "luck": 100},
        {"pigeon_type": 1, "luck": 100},
        {"pigeon_type": 1, "luck": 100},
    ],
    18: [
        {"pigeon_type": 3, "luck": 100},
        {"pigeon_type": 3, "luck": 100},
        {"pigeon_type": 3, "luck": 100},
        {"pigeon_type": 3, "luck": 100},
        {"pigeon_type": 3, "luck": 100},
    ],
    19: [
        {"pigeon_type": 1, "luck": 100},
        {"pigeon_type": 1, "luck": 100},
        {"pigeon_type": 2, "luck": 100},
        {"pigeon_type": 2, "luck": 100},
        {"pigeon_type": 3, "luck": 100},
    ],
}
