version: "3"

services:
  backend:
    image: python:3.10.7
    volumes:
      - ./backend/:/backend
    working_dir: /backend
    command: sh entrypoint.sh
    env_file:
      - .backend.env
    depends_on:
      - db
  db:
    image: postgres:15.2
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5435:5432
    env_file:
      - .db.env
  frontend:
    image: node:18.17.0
    env_file:
      - .frontend.env
    command: sh wrapper.sh
    working_dir: /frontend/
    volumes:
      - ./frontend/:/frontend
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    env_file:
      - .nginx.env
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/:/var/www/frontend
    depends_on:
      - backend
volumes:
  pgdata: