# Generated by Django 3.1.3 on 2021-02-06 17:19

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TR_Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_id', models.IntegerField(db_index=True, default=1)),
                ('effect_name', models.CharField(default='test', max_length=30)),
                ('is_active_effect', models.BooleanField(default=True)),
                ('has_value', models.BooleanField(default=True)),
                ('min_value', models.IntegerField(default=1)),
                ('max_value', models.IntegerField(default=1)),
                ('desc', models.CharField(default='test', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TR_Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField(db_index=True, default=1)),
                ('seeds', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('name', models.CharField(default='test', max_length=30)),
                ('min_drop_minute', models.IntegerField(default=0)),
                ('max_drop_minute', models.IntegerField(default=0)),
                ('min_feathers', models.IntegerField(default=0)),
                ('max_feathers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TR_Lvl_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField(db_index=True, default=1)),
                ('seeds_minute', models.IntegerField(default=0)),
                ('max_seeds', models.IntegerField(default=0)),
                ('max_droppings', models.IntegerField(default=0)),
                ('max_feathers', models.IntegerField(default=0)),
                ('max_pigeons', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='TR_Pigeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl_expedition', models.IntegerField(default=1)),
                ('coef_chance_rate', models.IntegerField(default=1)),
                ('pigeon_type', models.IntegerField(default=1)),
                ('pigeon_id', models.IntegerField(default=1)),
                ('src', models.CharField(default='test.png', max_length=30)),
                ('name', models.CharField(default='test', max_length=30)),
                ('min_atk', models.IntegerField(default=1)),
                ('max_atk', models.IntegerField(default=1)),
                ('min_life', models.IntegerField(default=1)),
                ('max_life', models.IntegerField(default=1)),
                ('min_shield', models.IntegerField(default=1)),
                ('max_shield', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1)),
                ('min_luck_1', models.IntegerField(default=1)),
                ('effect_1_chance', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('effect_1', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('min_luck_2', models.IntegerField(default=1)),
                ('effect_2_chance', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('effect_2', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField(default=1)),
                ('seeds', models.IntegerField(default=0)),
                ('droppings', models.IntegerField(default=0)),
                ('feathers', models.IntegerField(default=0)),
                ('military_score', models.IntegerField(default=0)),
                ('last_connected_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pigeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pigeon_type', models.IntegerField(default=1)),
                ('name', models.CharField(default='test', max_length=30)),
                ('pigeon_id', models.IntegerField(default=1)),
                ('luck', models.IntegerField(default=1)),
                ('element', models.IntegerField(default=1)),
                ('attack', models.IntegerField(default=1)),
                ('life', models.IntegerField(default=1)),
                ('shield', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=1)),
                ('droppings_minute', models.IntegerField(default=1)),
                ('feathers', models.IntegerField(default=1)),
                ('creation_time', models.DateTimeField(null=True)),
                ('active_time', models.DateTimeField(null=True)),
                ('effect_1_id', models.IntegerField(default=1)),
                ('effect_2_id', models.IntegerField(default=1)),
                ('effect_1_value', models.IntegerField(default=1)),
                ('effect_2_value', models.IntegerField(default=1)),
                ('is_open', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_attacker', models.BooleanField(default=False)),
                ('defender_pos', models.IntegerField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigeon_app.player')),
            ],
        ),
    ]
