# Generated by Django 3.1.3 on 2021-03-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attacking_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_attacked',
            field=models.IntegerField(default=-1),
        ),
    ]
