# Generated by Django 3.1.3 on 2020-12-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TR_Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField(db_index=True, default=1)),
                ('seeds', models.IntegerField(default=0)),
                ('name', models.CharField(default='test', max_length=30)),
            ],
        ),
    ]
