# Generated by Django 3.1.3 on 2022-10-01 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='attacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_player_atk', to='pigeon_app.player'),
        ),
        migrations.CreateModel(
            name='AdventureAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atk_tot_score', models.IntegerField(default=0)),
                ('atk_tot_phys', models.IntegerField(default=0)),
                ('atk_tot_magic', models.IntegerField(default=0)),
                ('atk_tot_shield', models.IntegerField(default=0)),
                ('def_tot_score', models.IntegerField(default=0)),
                ('def_tot_phys', models.IntegerField(default=0)),
                ('def_tot_magic', models.IntegerField(default=0)),
                ('def_tot_shield', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_victory', models.BooleanField(default=False)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_adventure', to='pigeon_app.adventure')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventureattack_player_atk', to='pigeon_app.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
