# Generated by Django 3.1.3 on 2020-12-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon_app', '0002_tr_expedition'),
    ]

    operations = [
        migrations.AddField(
            model_name='tr_expedition',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
