# Generated by Django 3.1.3 on 2021-11-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon_app', '0002_auto_20211125_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_id', models.IntegerField(default=0)),
                ('atk_tot_score', models.IntegerField(default=0)),
                ('atk_tot_phys', models.IntegerField(default=0)),
                ('atk_tot_magic', models.IntegerField(default=0)),
                ('atk_tot_shield', models.IntegerField(default=0)),
                ('def_tot_score', models.IntegerField(default=0)),
                ('def_tot_phys', models.IntegerField(default=0)),
                ('def_tot_magic', models.IntegerField(default=0)),
                ('def_tot_shield', models.IntegerField(default=0)),
                ('stolen_droppings', models.IntegerField(default=0)),
                ('atk_old_military_score', models.IntegerField(default=0)),
                ('atk_new_military_score', models.IntegerField(default=0)),
                ('def_old_military_score', models.IntegerField(default=0)),
                ('def_new_military_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_atk', to='pigeon_app.player')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_def', to='pigeon_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='AttackPigeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attacker', models.BooleanField(default=False)),
                ('phys_atk_bonus', models.IntegerField(default=0)),
                ('magic_atk_bonus', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigeon_app.attack')),
                ('pigeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigeon_app.pigeon')),
            ],
        ),
    ]
