# Generated by Django 3.1.3 on 2023-04-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon_app', '0002_player_protected_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_tutorial_done',
            field=models.BooleanField(default=False),
        ),
    ]
