# Generated by Django 3.1.3 on 2024-02-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon_app', '0003_auto_20230423_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nb_notifs',
            field=models.IntegerField(default=0),
        ),
    ]
