# Generated by Django 3.1.3 on 2021-12-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon_app', '0003_attack_attackpigeon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PvePigeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=-1)),
                ('pigeon_type', models.IntegerField(default=1)),
                ('name', models.CharField(default='test', max_length=30)),
                ('src', models.CharField(default='test', max_length=30)),
                ('pigeon_id', models.IntegerField(default=1)),
                ('lvl', models.IntegerField(default=1)),
                ('luck', models.IntegerField(default=1)),
                ('phys_atk', models.IntegerField(default=1)),
                ('magic_atk', models.IntegerField(default=1)),
                ('shield', models.IntegerField(default=0)),
                ('droppings_minute', models.IntegerField(default=1)),
                ('feathers', models.IntegerField(default=1)),
                ('creation_time', models.DateTimeField(null=True)),
                ('active_time', models.DateTimeField(null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_in_team', models.BooleanField(default=False)),
            ],
        ),
    ]
