# Generated by Django 3.1.3 on 2021-12-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon_app', '0004_pvepigeon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField(default=0)),
                ('encounter', models.IntegerField(default=0)),
                ('nb_tries', models.IntegerField(default=0)),
                ('is_success', models.BooleanField(default=False)),
                ('reward_droppings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigeon_app.player')),
            ],
        ),
    ]
