# Generated by Django 3.1.3 on 2020-12-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon_app', '0004_auto_20201216_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigeon',
            name='is_defender',
        ),
        migrations.AddField(
            model_name='pigeon',
            name='defender_pos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tr_lvl_info',
            name='seeds_minute',
            field=models.IntegerField(default=0),
        ),
    ]
