# Generated by Django 3.1.3 on 2021-01-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon_app', '0005_auto_20201224_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tr_pigeon',
            name='max_drop_minutes',
        ),
        migrations.RemoveField(
            model_name='tr_pigeon',
            name='max_feathers',
        ),
        migrations.RemoveField(
            model_name='tr_pigeon',
            name='min_drop_minutes',
        ),
        migrations.RemoveField(
            model_name='tr_pigeon',
            name='min_feathers',
        ),
        migrations.AddField(
            model_name='tr_expedition',
            name='max_drop_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tr_expedition',
            name='max_feathers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tr_expedition',
            name='min_drop_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tr_expedition',
            name='min_feathers',
            field=models.IntegerField(default=0),
        ),
    ]
