# Generated by Django 3.1.3 on 2021-01-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon_app', '0006_auto_20210121_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='tr_lvl_info',
            name='max_pigeons',
            field=models.IntegerField(default=10),
        ),
    ]
